name: Benchmarks(Bundle Size|Performance)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1
      - name: Installing packages
        run: yarn
      - name: Run benchmarks
        run: yarn benchmarks
